### PR TITLE
Make @connection generate required PageInfo in connection

### PR DESCRIPTION
**Pull request by manymotes**
Pull request checklist
----

- [ ] Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md)
- [ ] Consider creating a discussion on the [discussion forum](https://github.com/Netflix/dgs-framework/discussions)
  first
- [ ] Make sure the PR doesn't introduce backward compatibility issues
- [ ] Make sure to have sufficient test cases

Pull Request type
----

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Other (please describe):

Changes in this PR
----

_Describe the new behavior from this PR, and why it's needed_
Issue #

Alternatives considered
----

_Describe alternative implementation you have considered_

### CODE REVIEW

**Comment by congotej** [comment]
Thanks for submitting this @manymotes! Looking into it and will get back to you by tomorrow.

**Review by congotej — APPROVED** [review]
Everything looks good here! Can you please rebase?

**Comment by manymotes** [comment]
rebased

**Comment by manymotes** [comment]
Hey, thanks a lot for getting this done so quickly. It's kind of a small detail, but my UI team can be a little picky about this stuff.

**Pull request merged**
