### PR TITLE
Make fed resolver always apply configured exception handler

### PR DESCRIPTION
**Pull request by raptros**
Pull request checklist
----

- [x] Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md)
- [x] Consider creating a discussion on the [discussion forum](https://github.com/Netflix/dgs-framework/discussions) first
- [x] Make sure the PR doesn't introduce backward compatibility issues
- [x] Make sure to have sufficient test cases

Pull Request type
----

- [x] Bugfix

Changes in this PR
----

Issue #966 

Ensures that a configured exception handler will be applied to exceptions that occurred within eg a Mono or CompleteableFuture execution.

The tests specifically for exception handling did not previously verify that the custom handler was called in all cases; added a check to verify it was called.

Had to make all of the tests in that suite provide a more fully configured DFE in order to get them to pass - there was an NPE in DefaultDataFetcherExceptionHandler when the ExecutionStepInfo wasn't present.

Alternatives considered
----

Considered trying to detect and special-case a not-fully configured DFE, but determined that the problem was the tests.

Considered not extracting causes from additional exception types, but after checking that CompletableFuture does wrap exceptions (and Mono does not), decided to add the extra extraction.

### CODE REVIEW

**Comment by srinivasankavitha** [comment]
Thanks for the PR contribution!

**Review by srinivasankavitha — APPROVED** [review]

**Comment by raptros** [comment]
tyvm. I see that the checks have passed - what's the cycle for when yall merge things?

**Comment by srinivasankavitha** [comment]
> 

We have a couple PRs coming up, so likely end of this week or early next week we'll do a release.

**Comment by raptros** [comment]
Thank you!

**Pull request merged**
