### PR TITLE
Add more IDE project specific files into gitignore

### PR DESCRIPTION
**Pull request by hantsy**
Pull Request type
----

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [X] Other (please describe):

Changes in this PR
----

These files are generated by IDEs when opening a Gradle based projects.

They are common files to be ignored in a Java project.

If you generate an empty project from Spring initializr or create an empty project on Github, it also generate a gitignore file include all IDE specific files which should not be managed by Git.

### CODE REVIEW

**Comment by berngp** [comment]
I think most of these belong to a global git ignore and are not specific to this project.

**Comment by srinivasankavitha** [comment]
I agree with @berngp. These files don't seem related to the dgs framework.

**Comment by hantsy** [comment]
I do not set a global gitignore, when opening this project with VsCode, it
will generate Java related project files(similar to Eclipse project).

*Hantsy Bai*

Self-employed consultant, fullstack developer, agile coach

GitHub: https://github.com/hantsy

Twitter: ***@***.***
Medium: ***@***.***

**Comment by srinivasankavitha** [comment]
I see, so these are generated when using VSCode only?

**Comment by berngp** [comment]
If we could express that the idea of the PR is to better support other IDE's and ignore their project specific generated files, then I think its ok. As is the PR stands without any description.

**Comment by hantsy** [comment]
These files are generated by IDEs when opening a Gradle based projects. 

They are common files to be ignored in a Java project. 

 If you generate an emtpy project from Spring initializr or create an empty project on Github, it also generate a gitignore file include all IDE specific files which should not be managed by Git.

**Review by berngp — APPROVED** [review]

**Review by srinivasankavitha — APPROVED** [review]

**Pull request merged**
