### PR TITLE
Rename packages from autoconfig -> autoconfigure

### PR DESCRIPTION
**Pull request by bono007**
@paulbakker @berngp long time no see 👋🏻. I have been meaning to circle back and make this refactor - the day job been keeping me too busy 😼 

Fixes gh-213

### CODE REVIEW

**Comment by berngp** [comment]
Thanks @bono007, and sorry for taking some time to look into this.

**Comment by bono007** [comment]
> Thanks @bono007, and sorry for taking some time to look into this.

NP @berngp . I am going to try to make some additional contributions this weekend as well.

**Comment by berngp** [comment]
Rolling back this change. Will reconsider when we have our 4.x release.

**Comment by bono007** [comment]
@berngp I am guessing people got hit by the package name changes? I had some original concern about this but I think we decided to make the move as it was in the auto-config classes. But yeh, I think this is better suited for 4.x as well.

**Comment by paulbakker** [comment]
@bono007  What we forgot about is that folks use the DgsAutoconfig class in `@SpringBootTest(classes = ...)`. Other than that you woulder depend on it directly, but it didn't seem right to break test compilation in a minor release.

**Comment by berngp** [comment]
@bono007 we discussed adding a _test slice_ to prevent folks from directly referencing the auto-configuration. Regardless I think we can include this change for the 4.x release.

**Comment by bono007** [comment]
Agreed on both of your points @paulbakker and @berngp .

**Pull request merged**
