### PR TITLE
Added ability to configure log level in subscription error

### PR DESCRIPTION
**Pull request by nkonev**
Pull Request type
----
- [x] Feature

Changes in this PR
----
Added ability to configure log level in subscription error

### CODE REVIEW

**Review by srinivasankavitha — COMMENTED** [review]
Changes look good. Did you add this because you consider the subscription error message a non-error?

**Comment by nkonev** [comment]
@srinivasankavitha 
Yes

**Review by srinivasankavitha — APPROVED** [review]

**Comment by srinivasankavitha** [comment]
Ok, could you please rebase. We can merge the PR after that.

**Comment by nkonev** [comment]
Done

**Pull request merged**
