### PR TITLE
feature/time-tracker-boost: Add total time or duration methods that log despite error

### PR DESCRIPTION
**Pull request by anticipasean**
Add measurement functional type and base set of time-elapsed measurement on action methods to TimeTracer that log total time or duration even when error occurs

Pull request checklist
----

- [x] Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md)
- [x] Consider creating a discussion on the [discussion forum](https://github.com/Netflix/dgs-framework/discussions)
  first
- [x] Make sure the PR doesn't introduce backward compatibility issues
- [x] Make sure to have sufficient test cases

Pull Request type
----

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe):

Changes in this PR
----
- Add measurement functional type and base set of time-elapsed measurement on action methods to TimeTracer that log total time or duration even when error occurs
- Create unit tests for new measurement and logger extension functions on TimeTracer

_Describe the new behavior from this PR, and why it's needed_

Issue # NA

No migration of existing calls to the com.netflix.graphql.dgs.internal.utils.TimeTracer#logTime function were done as part of this PR, so no change in behavior of the application should be observed at compile time or runtime (provided that, of course, my local testing environment has the expected configuration for this repo). I will leave it to the repo owners to decide whether to migrate those function calls to make use of one of the new functions on this TimeTracer singleton.

I observed that the com.netflix.graphql.dgs.internal.utils.TimeTracer#logTime function does not log the total time when an error within one of its various referenced action blocks occurs and think it will be helpful to others if it still did log those times, especially if that duration takes suspiciously long in  the case of an error but is otherwise quick in the success case.

I also think the new syntax is a little cleaner in Kotlin when function calls like that one,  com.netflix.graphql.dgs.internal.utils.TimeTracer#logTime, have their one function input parameter at the end of their parameter sets so the block can hang off the end of the function call and in some cases, with extension functions, the Logger parameter can become _implied_ through a receiver function call.

(I am working on a functional feature engineering pipeline in my repo [funcify-feature-eng](https://github.com/anticipasean/funcify-feature-eng) and am considering using DGS for at least part of it but need to flesh out certain other functional typing and pipelining constructs before I get to the GraphQL piece. So, that's how I came across this timing component)

Alternatives considered
----
-  Since these changes only affect a very specific class within the com.netflix.graphql.dgs.internal package, it seemed to be more fun to present the more extensive solution first, one with some syntactic sugar examples, before posting a basic but possibly preferred (depending on the repo-owners) simple `try { ... } catch { ... }` block around the `action.invoke()` piece in the existing com.netflix.graphql.dgs.internal.utils.TimeTracer#logTime

_Describe alternative implementation you have considered_
- A simple `try { ... } catch { ... }` block around the `action.invoke()` piece in the existing com.netflix.graphql.dgs.internal.utils.TimeTracer#logTime

### CODE REVIEW

**Comment by berngp** [comment]
Hi @anticipasean, did you looked at `graphql-dgs-spring-boot-micrometer`?  To provide measurements we are leveraging _Micrometer_, checkout our [Metrics Out of the Box](https://netflix.github.io/dgs/advanced/instrumentation/#metrics-out-of-the-box)

**Comment by smccarron-prosper** [comment]
Hey @berngp,  thanks for the reference! I am just getting started with a new project that I am considering using DGS for, at least one of its components. I am still exploring all of the configuration options, possible dependencies, etc. for this use case. The `graphql-dgs-spring-boot-micrometer` module definitely appears to cover the more important metrics I want to capture and track: the query and mutation times.

With that said, the `graphql-dfs` and `graphql-dgs-spring-webmvc` modules are still using com.netflix.graphql.dgs.internal.utils.TimeTracer#logTime method to log several some action times: 
* [DgsRestController-L182](https://github.com/Netflix/dgs-framework/blob/cb514fc2110a8fabed4841bdea3b26543bb41615/graphql-dgs-spring-webmvc/src/main/kotlin/com/netflix/graphql/dgs/mvc/DgsRestController.kt#L182)
* [DgsRestController-L207](https://github.com/Netflix/dgs-framework/blob/cb514fc2110a8fabed4841bdea3b26543bb41615/graphql-dgs-spring-webmvc/src/main/kotlin/com/netflix/graphql/dgs/mvc/DgsRestController.kt#L207)
* [DefaultDgsGraphQLContextBuilder-L36](https://github.com/Netflix/dgs-framework/blob/cb514fc2110a8fabed4841bdea3b26543bb41615/graphql-dgs/src/main/kotlin/com/netflix/graphql/dgs/internal/DefaultDgsGraphQLContextBuilder.kt#L36)

If you do plan to still log those times and/or others that fall outside the scope of micrometer tagging or GraphQL instrumentation specs e.g. how long it takes to build the dgs graphql context in the context builder, then it wouldn't hurt to use this measurement code in TimeTracer since it's only in the internal package / API and helpful for measuring any synchronous but potentially delayed actions (The asynchronous ones obviously require a bit more finesse to measure properly). 

Is the plan to have micrometer eventually cover these other use cases as well i.e. start-up schema wiring, context creation, context updates, etc.?

**Comment by anticipasean** [comment]
Hey @berngp,  thanks for the reference! I am just getting started with a new project that I am considering using DGS for, at least one of its components. I am still exploring all of the configuration options, possible dependencies, etc. for this use case. The `graphql-dgs-spring-boot-micrometer` module definitely appears to cover the more important metrics I want to capture and track: the query and mutation times.

With that said, the `graphql-dfs` and `graphql-dgs-spring-webmvc` modules are still using com.netflix.graphql.dgs.internal.utils.TimeTracer#logTime method to log several some action times: 
* [DgsRestController-L182](https://github.com/Netflix/dgs-framework/blob/cb514fc2110a8fabed4841bdea3b26543bb41615/graphql-dgs-spring-webmvc/src/main/kotlin/com/netflix/graphql/dgs/mvc/DgsRestController.kt#L182)
* [DgsRestController-L207](https://github.com/Netflix/dgs-framework/blob/cb514fc2110a8fabed4841bdea3b26543bb41615/graphql-dgs-spring-webmvc/src/main/kotlin/com/netflix/graphql/dgs/mvc/DgsRestController.kt#L207)
* [DefaultDgsGraphQLContextBuilder-L36](https://github.com/Netflix/dgs-framework/blob/cb514fc2110a8fabed4841bdea3b26543bb41615/graphql-dgs/src/main/kotlin/com/netflix/graphql/dgs/internal/DefaultDgsGraphQLContextBuilder.kt#L36)

If you do plan to still log those times and/or others that fall outside the scope of micrometer tagging or GraphQL instrumentation specs e.g. how long it takes to build the dgs graphql context in the context builder, then it wouldn't hurt to use this measurement code in TimeTracer since it's only in the internal package / API and helpful for measuring any synchronous but potentially delayed actions (The asynchronous ones obviously require a bit more finesse to measure properly). 

Is the plan to have micrometer eventually cover these other use cases as well i.e. start-up schema wiring, context creation, context updates, etc.?

**Comment by anticipasean** [comment]
Just curious, which team works on this repo at Netflix? Lots of the examples feature entities like _shows_ and _reviews_---Netflix's customer-facing company _product_ types---but I would figure creating data pipelines that do feature engineering for machine learning models and business statistics like what I've been working on---entities like _transunion_credit_report_ and _transunion_tradeline_features_ with fields like _adj_rev_spend_idx_1y_ (_adjusted revolving spend index over past year_)---would be a pretty cool use case and feature set for DGS. The current set of opensource tools out there require a lot of stitchwork to pull together: Apache Spark, Apache Druid, Apache Beam, Hasura, Spotify Scio, etc. and house under one GraphQL schema roof (or federated set of GraphQL schemata).

**Comment by srinivasankavitha** [comment]
The examples are based on product types because the DGS framework primarily
started as solving for Netflix's Studio API. Most of our DGSs are in that
space, with a few more coming up for internal usages. We haven't yet come
across any business use case for adopting this for data pipelines for
machine learning. We do have an examples section in our docs with
contributions from the community, so if you have ideas there, we would
welcome any additional examples for such new use cases.
https://netflix.github.io/dgs/examples/#community-contributions

**Comment by berngp** [comment]
I think that logging is not really a scalable way to express measurements. So, to answer your question, I think that we should replace them. I do see value on abstracting the observations of actions in such a manner that they can be easily leveraged for metrics via Micrometer,or other use cases, such as tracing via Brave/Zipkin.


PS there is a Micrometer Meter Registry that logs measurements to a file.

**Pull request closed without merging**
