### PR TITLE
open DefaultDataFetcherExceptionHandler

### PR DESCRIPTION
**Pull request by sbilello**
Pull request checklist
----

- [X] Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md)
- [ ] Consider creating a discussion on the [discussion forum](https://github.com/Netflix/dgs-framework/discussions)
  first
- [ ] Make sure the PR doesn't introduce backward compatibility issues
- [ ] Make sure to have sufficient test cases

Pull Request type
----

- [ ] Bugfix
- [ ] Feature
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe):

Changes in this PR
----

_Describe the new behavior from this PR, and why it's needed_
I would like to extend `DefaultDataFetcherExceptionHandler` to reduce boilerplate code

Alternatives considered
----

_Describe alternative implementation you have considered_

Copying and Paste in another `Class`

### CODE REVIEW

**Review by srinivasankavitha — COMMENTED** [review]
Have you looked at these docs? This should let you add custom exception handling: https://netflix.github.io/dgs/error-handling/#mapping-custom-exceptions

**Comment by paulbakker** [comment]
@srinivasankavitha I think the request is to make it possible to _extend_ the default behavior. 
If you create a custom exception handler, it replaces the default behavior currently.

@sbilello I'm not sure extending the default is the best option to achieve this. I'll look into some options.

**Comment by sbilello** [comment]
@srinivasankavitha I wanted to extend the current exception handler with my logic and not copy and paste the current logic. Right now that class is instantiated by the `DgsAutoConfiguration` conditionally `@ConditionalOnMissingBean`, 
so my handler would replace the current one. I wanted to add logic to the existing one by extending it with a child class. Thanks for your review!

**Comment by srinivasankavitha** [comment]
Actually what I meant to point out is that you can delegate to the default
exception handler in your custom exception handler. Thus you won't need to
copy any logic. The docs I linked do mentioned "either extend or delegate"
which is misleading. The recommended pattern is to just add your own
exception handler and delegate to the default where applicable as shown
here:
https://netflix.github.io/dgs/error-handling/#mapping-custom-exceptions

I will fix the docs as well.

**Comment by sbilello** [comment]
Thanks, @srinivasankavitha!

**Pull request closed without merging**
