### PR TITLE
Serialize Map types in GraphQLQuery

### PR DESCRIPTION
**Pull request by richardcresswell**
Pull request checklist
----

- [x] Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md)
- [ ] Consider creating a discussion on the [discussion forum](https://github.com/Netflix/dgs-framework/discussions)
  first
- [x] Make sure the PR doesn't introduce backward compatibility issues
- [x] Make sure to have sufficient test cases

Pull Request type
----

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe):

Changes in this PR
----
Issue #290

Support Maps in GraphQLQuery serialization.  This is useful for JSON and Object scalars.

Alternatives considered
----

n/a

### CODE REVIEW

**Comment by richardcresswell** [comment]
Did the CI checks have some kind of environmental issue not related to this pull request?

**Comment by paulbakker** [comment]
> Did the CI checks have some kind of environmental issue not related to this pull request?

Yes, I think so. Several other builds also failed.

**Comment by paulbakker** [comment]
@richardcresswell I've restarted the builds, fingers crossed that just fixes it

**Comment by berngp** [comment]
I'm looking at the build failures. Will disable test-reporting for now to get this going.

**Comment by berngp** [comment]
@richardcresswell could you please rebase against master?

**Comment by richardcresswell** [comment]
Should be all set.

**Comment by berngp** [comment]
@paulbakker @richardcresswell boggles the mind that the CI Workflows are still trying to _Publish the Tests_. This was disabled and both master as well as @richardcresswell 's branch reflect it.

**Comment by berngp** [comment]
The code changes look fine and and the project build as well. The failures are based on the failure to publish the JUnit Reports.
There is a caveat on using the `pull_request` action that I was not aware and affects the publishing of such reports, if the PR comes from an external fork. In addition, it looks like this build is being triggered against the Github actions available when this PR was created instead of the ones available in master that have such _publishing_ disabled.

Ref.

1. https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
1. https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Comment by berngp** [comment]
@paulbakker @richardcresswell , the build is green.

**Review by berngp — APPROVED** [review]

**Comment by berngp** [comment]
Thanks @richardcresswell for the PR and patience with the build.

**Comment by richardcresswell** [comment]
Thanks for merging!  So we can plan on our side, do you know when you will be publishing the next RC or release?

**Comment by srinivasankavitha** [comment]
@richardcresswell - we will release this week, likely in the next day or two.

**Pull request merged**
