### PR TITLE
Upgrade to Spring 5.3.12 and Spring Boot 2.5.6

### PR DESCRIPTION
**Pull request by berngp**
Pull Request type
----

- [ ] Bugfix
- [x] Feature
- [x] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Other (please describe):

Changes in this PR
----

Upgrade to Spring 5.3.12 and Spring Boot 2.5.6

### CODE REVIEW

**Comment by GFriedrich** [comment]
Please also ensure to update the Spring Cloud version as the Hoxton release train is only compatible to a Spring Boot version up to 2.3.x (see https://spring.io/projects/spring-cloud).

**Comment by berngp** [comment]
Thanks for pointing this out @GFriedrich, will update the Spring Cloud version.

We are holding on this for now since we don't want the framework to force folks adopt Spring Boot 2.5. Developers can decide to adopt it and the framework works well with it, even though it expresses a transitive to 2.3.

**Comment by GFriedrich** [comment]
Ah good to know @berngp, thanks for the info.
Is this already documented somewhere?
If not some compatibility table would be nice I guess.

**Comment by berngp** [comment]
@GFriedrich created https://github.com/Netflix/dgs-framework/issues/760 to track it.

**Comment by berngp** [comment]
Closing this PR in favor for a new effort to move the framework to...
Spring Boot 2.6.x
Spring Framework 5.3.x
Spring Security 5.6.x
Spring Cloud 2021.0.1
Jackson 2.13.x
Kotlin 1.6.21

**Pull request closed without merging**
