### PR TITLE
Support of PreparsedDocumentProvider in  DgsWebFluxAutoConfguration

### PR DESCRIPTION
**Pull request by pushpagarwal**
Pull request checklist
----

- [ ] Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md)
- [ ] Consider creating a discussion on the [discussion forum](https://github.com/Netflix/dgs-framework/discussions)
  first
- [X] Make sure the PR doesn't introduce backward compatibility issues
- [ ] Make sure to have sufficient test cases

Pull Request type
----

- [X] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe):

Changes in this PR
----

Please refer to https://github.com/Netflix/dgs-framework/issues/50. Support of PreparsedDocumentProvider was added through PR https://github.com/Netflix/dgs-framework/pull/583.
Above PR added it to DefaultDgsReactiveQueryExecutor but missed changes in DgsWebFluxAutoConfiguration.
In this PR, we are fixing that so that WebFlux application can define own implementation PreparsedDocumentProvider.

Alternatives considered
----

### CODE REVIEW

**Comment by pushpagarwal** [comment]
It seems PR https://github.com/Netflix/dgs-framework/pull/776 was raised for same purpose but unfortunately reverted later. 
It would be better to use PR https://github.com/Netflix/dgs-framework/pull/776 again.

**Comment by berngp** [comment]
@pushpagarwal thanks for opening the PR again. I am not sure what happened to be honest. I don't think any of us reverted it.

**Comment by saravind-hotstar** [comment]
@berngp Please could you let us know, when this will be merged

**Comment by berngp** [comment]
PR available in 4.9.12

**Pull request merged**
