### PR TITLE
Increment error metric

### PR DESCRIPTION
**Pull request by spellew**
Recent PR accidentally removed the increment call from the gql.error metric. Fixed bug and improved tests to ensure metric count is incremented.

### CODE REVIEW

**Comment by rhino88** [comment]
@kilink are we able to cut a new release with this change? This issue is impacting observability for us in production.

**Comment by deweyjose** [comment]
This is impacting our teams in production as well. Any timelines on release?

**Comment by evanmalmud** [comment]
Same here! I want to fix our metrics!

**Comment by Emily** [comment]
@deweyjose @evanmalmud v8.3.1 is releasing right now!

**Comment by deweyjose** [comment]
Thank you @Emily !

**Pull request merged**
