### PR TITLE
Removes the exclusion of json-smart from graphql-dgs-client

### PR DESCRIPTION
**Pull request by bono007**
@paulbakker 

Fixes gh-73

### CODE REVIEW

**Comment by paulbakker** [comment]
Thanks @bono007 !

**Comment by bono007** [comment]
> Thanks @bono007 !

No worries @paulbakker - had I known about `spring-data-common` use (partial swap of mapping provider but not json provider) and the fact that json-path does not really let you "swap" providers easily (and remove them from the classpath) I would not have submitted the proposal until at least one of the above were resolved. Sorry for introducing the toil. 

Once again, another learning of the "Dependencies are hard" variety. :)

**Comment by paulbakker** [comment]
Yeah, same here, I didn't expect this problem either. 
We still made the code changes so that the framework doesn't depend on json-smart anymore though, so at least the result is that you now _can_ exclude the dependency.

**Comment by bono007** [comment]
> We still made the code changes so that the framework doesn't depend on json-smart anymore though, so at least the result is that you now can exclude the dependency.

Absolutely. It was not time wasted IMO.

**Pull request merged**
