### PR TITLE
#1058: Correct error types for bad user input in micrometer

### PR DESCRIPTION
**Pull request by antholeole**
Pull request checklist
----

- [X] Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md)
- [X] Make sure the PR doesn't introduce backward compatibility issues
- [X] Make sure to have sufficient test cases

Pull Request type
----

- [X] Bugfix
- [x] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe):

Changes in this PR
----
In general I'd recommend reviewing commit by commit.

- `MissingFederatedQueryArgument` reported unknown to micrometer (fix [here](https://github.com/Netflix/dgs-framework/commit/cb1cde640045839298367e6b5f04087b88342e28)):  `MissingFederatedQueryArgument` and a few other Dgs exceptions now inherit from `DgsException`: if we catch a `DGSException`, we know that it is typed properly, so we don't have to special case on a bunch of exception types

- `The query is null or empty.` is not getting reported to micrometer (fix [here](https://github.com/Netflix/dgs-framework/commit/461ffb95126cb71d91fca4720b8b0e4d4b89f8e1)): this one was a bit tricky, since `BaseDgsQueryExecutor` would short circuit on an empty query with a custom error. I opted to remove this logic because an empty query is effectively the same thing as a query with just a single character but would turn up completely different errors; if we remove this special case logic, the error falls through, micrometer reports it and the user sees a `SyntaxError`. lmk if there is a better way to handle this (I tried manually passing to instrumentation but it was very clunky)
 
- `ValidationError` reporting as unknown to micrometer (fix [here](https://github.com/Netflix/dgs-framework/commit/7a5dddbd2baf9cbd0d84da7ba2c7deb244d657f0)): Special cased it

- Re-added micrometer to example project (fix [here](https://github.com/Netflix/dgs-framework/commit/412f7eeac12db2adc296cf8f1e5ac3abd5b4f829)): as @srinivasankavitha and I discussed, this should be re-added

lmk thoughts and additional test cases. The old test cases covered most of these changes, the only new feature is the `DGSException` which I added a test case for.

### CODE REVIEW

**Comment by berngp** [comment]
Thanks for the PR. The idea of introducing a `DgsException` makes sense and simplifies the code handling them quite a bit in the [DefaultDataFetcherExceptionHandler.kt](https://github.com/Netflix/dgs-framework/pull/1248/files#diff-cbec39732fd94c71343fc88a8a9a2c97e7fc9946338e25f0bfc20ee0e8b16e8e). What I'll do is merge this PR in the [feature/refactor-metrics](https://github.com/Netflix/dgs-framework/tree/feature/refactor-metrics) branch and look at the failing text.

**Comment by antholeole** [comment]
Hey! Sorry about the failing tests - I was going to take time to look at them but got caught up with midterms. If you want to take it over that’s fine, but it’s on the agenda for me. On Oct 10, 2022, at 4:19 PM, Bernardo Gomez Palacio ***@***.***> wrote:﻿
Merged #1248 into feature/refactor-metrics.

**Comment by berngp** [comment]
@antholeole, the branch [feature/refactor-metrics](https://github.com/Netflix/dgs-framework/tree/feature/refactor-metrics) is based in your PR with additional small changes. There is a caveat around how we return errors when the request doesn't have a `query`. After discussing this with @srinivasankavitha, we both agree that the best approach is to change the code, in this case the `BaseDgsQueryExecutor` to return a known exception that will be caught by the `DgsRestController` and the `DefaultDgsWebfluxHttpHandler` to return 400. The response should follow the GraphQL standard of returning the following payload

```
{
                  "errors":[
                    {
                      "message": "GraphQL operations must contain a non-empty `query`.",
                      "locations":[],
                      "extensions": {
                        "errorType":"BAD_REQUEST"
                      }
                    }
                  ]
} 
```

How does it impact metrics?
If the request doesn't have a `query` it will not be captured as part of the `gql.query` metrics, since it is not really a query. That said, if we do return a 400, it will properly show in the Spring MVC and Spring Webflux [metrics](https://docs.spring.io/spring-boot/docs/2.6.x/reference/htmlsingle/#actuator.metrics.supported.spring-mvc).

If you want, and please let us know, you could implement the changes in the `BaseDgsQueryExecutor`, `DefaultDgsWebfluxHttpHandler` and `DgsRestController` to return a 400. This will impact the tests in both the`MalformedQueryContentTest.kt` used by webfux and mvc respectively. 

Please feel free to
1. checkout the `feature/refactor-metrics` branch
2. use that as your base branch
3. squahs your changes
4. send a PR targeting master.

ref.
https://github.com/Netflix/dgs-framework/compare/feature/refactor-metrics?expand=1

**Comment by antholeole** [comment]
Sure, I'll take that approach - seems the most correct and clever. I'll try to have a PR submitted by the end of week, perhaps earlier

**Comment by berngp** [comment]
Thank you!

**Pull request merged**
